# Generated by Django 5.1.6 on 2025-03-05 06:55

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_content_metadata_content_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('pageadmin', 'Page Admin')], default='pageadmin', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='core_catego_name_6ef604_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='core_catego_slug_a504e5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='core_commen_created_97080c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_approved'], name='core_commen_is_appr_a7c29f_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['title'], name='core_conten_title_bbbdf4_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['created_at'], name='core_conten_created_9c8460_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['published_at'], name='core_conten_publish_c3e69f_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_conten_search__dce135_gin'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='core_user_user_ty_e1e849_idx'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.CheckConstraint(condition=models.Q(('published_at__isnull', False), ('is_published', False), _connector='OR'), name='published_content_must_have_published_at'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='core.category'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='core_docume_title_5a80f0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='core_docume_uploade_e13ffd_idx'),
        ),
    ]
