# Generated by Django 5.1.6 on 2025-03-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contents', to='core.category'),
        ),
    ]
