# Generated by Django 5.1.6 on 2025-03-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='featured_image',
        ),
    ]
